name: SteamAppUpdate
inputs:
  steamcmd:
    required: true
  appid:
    required: true
  username:
    required: true
  password:
    required: true
  configvdf:
    required: true
runs:
  using: "composite"
  steps:
    # - name: Check PWD
    #   shell: bash
    #   run: |
    #     pwd
    #     ls -la .
    #     ls -la ~
    #     ls -la ~/SteamCMD
    - name: Steam App Update
      shell: bash
      env:
        STEAMCMD:  ${{ inputs.steamcmd }}
        APPID:     ${{ inputs.appid }}
        USERNAME:  ${{ inputs.username }}
        PASSWORD:  ${{ inputs.password }}
        CONFIGVDF: ${{ inputs.configvdf }}
      run: |
        ls -la ~
        ~/SteamCMD/steamcmd.sh +quit
        ls -la ~
        mkdir ~/Steam/config
        echo "$CONFIGVDF" | base64 -d > "~/Steam/config/config.vdf"
        ~/SteamCMD/steamcmd.sh +login $USERNAME +app_update $APPID +quit