name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    # - name: Download SteamCMD
    #   run: |
    #     sudo apt-get install lib32gcc-s1
    #     mkdir ~/SteamCMD
    #     cd ~/SteamCMD
    #     curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -

    # - name: Setup SteamCMD
    #   env:
    #     CONFIGVDF: ${{ secrets.steam_config_vdf }}
    #   run: |
    #     ~/SteamCMD/steamcmd.sh +quit
    #     echo "$CONFIGVDF" | base64 -d > ~/Steam/config/config.vdf

    # - name: Download Portal
    #   env:
    #     USERNAME: ${{ secrets.steam_username }}
    #     APPID:    400
    #   run: |
    #     ~/SteamCMD/steamcmd.sh +login "$USERNAME" +app_update "$APPID" +quit
    


    # - uses: actions/checkout@v4
    
    - name: Checkout portal64-still-alive
      run: |
        sudo apt install git -y
        git clone https://github.com/mwpenny/portal64-still-alive.git portal64
        cd portal64

    - name: Check result
      run: |
        pwd
        ls -la .
