name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Install SteamCMD (manually)
      run: |
        sudo apt-get install lib32gcc-s1
        mkdir ~/SteamCMD && cd ~/SteamCMD
        curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -

    - name: Check SteamCMD
      run: |
        ls -l ~/SteamCMD

    # - name: Install SteamCMD (Debian)
    #   run: |
    #     sudo apt update
    #     sudo apt install software-properties-common
    #     sudo apt-add-repository non-free
    #     sudo dpkg --add-architecture i386
    #     sudo apt update
    #     sudo apt install steamcmd
    
    - uses: actions/checkout@v4

    # - name: configure
    #   run: ./configure

    # - name: Install SteamCMD (Ubuntu)
    #   run: |
    #     sudo add-apt-repository multiverse
    #     sudo dpkg --add-architecture i386
    #     sudo apt update
    #     sudo apt install steamcmd

    # - name: Setup steamcmd
    #   uses: CyberAndrii/setup-steamcmd@v1

    # - name: Try download game from Steam
    # #   env:
    # #     MY_SECRET: ${{ secrets.my_secret }}
    #   # run: steamcmd +force_install_dir ~/steam +login anonymous +app_update "$MY_SECRET" +quit
    #   # run: steamcmd +force_install_dir ~/steam +login anonymous +app_update 1337 +quit
    #   run: steamcmd +login anonymous +app_update 1337 validate +quit
        
    - uses: ./
      with:
        my-secret: ${{ secrets.my_secret }}

    - name: Run make
      run: |
        cd makefiledemo
        make

    # - name: Run check
    # # - shell: bash
    #   env:
    #     MY_SECRET: ${{ secrets.my_secret }}
    #   run: |
    #     cd makefiledemo; make check ARG="$MY_SECRET"

    # - name: Run distcheck
    #   run: make distcheck
