name: Test Multi-Jobs

on:
  workflow_dispatch

jobs:
  write:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: |
        cd makefiledemo
        make
        ls -la
      
  read:
    runs-on: ubuntu-latest
    steps:
    - name: read
      run: |
        ls -la
