name: Test Multi-Jobs

on:
  workflow_dispatch

jobs:
  write:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: |
        cd makefiledemo
        make
        ls -la
        ./main
    - uses: actions/upload-artifact@v4
      with:
        name: write
        path: makefiledemo/main
      
  read:
    runs-on: ubuntu-latest
    needs: write
    steps:
    - name: read
      run: |
        ls -la
